[package]
name = "editoriaux"
version = "0.1.0"
edition = "2021"

[lib]
harness = false
name = "mylib"
path = "src/lib/mod.rs"

[[bin]]
name = "editoriaux"
path = "src/main.rs"

[dependencies]
reqwest = { version = "0.11.13", features = ["blocking"] }
scraper = "0.14.0"
url = "2.3.1"
